from __future__ import with_statement
from string import Template
import re, fnmatch, os

TEST_FUNC_REGEX = r"^(void\s+(test_%s__(\w+))\(\s*(void)?\s*\))\s*\{"

CLAY_BOILERPLATE = Template(
r"""
/*
 * This is an autogenerated file. Do not modify
 */

#include "clay.h"

${extern_declarations}

${test_callbacks}

static const struct clay_suite _all_suites[] = {
	${test_suites}
};

int main(int argc, char *argv[])
{
	return clay_test(
		argc, argv, _all_suites,
		sizeof(_all_suites)/sizeof(_all_suites[0]));
}
""")

TEMPLATE_CALLBACKS = Template(
r"""
static const struct clay_func _${suite_name}_tests[] = {
	${callbacks}
};
""")

TEMPLATE_SUITE = Template(
r"""
	{
		"${clean_name}",
		${initialize},
		${cleanup},
		_${suite_name}_tests,
		${test_count}
	}
""")

class ClayTestBuilder:
	def __init__(self, folder_name):
		self.declarations = []
		self.callbacks = []
		self.suites = {}

		file_list = os.listdir(folder_name)
		for fname in fnmatch.filter(file_list, "*.c"):
			with open(fname) as f:
				self._process_test_file(fname, f.read())

	def render(self):
		return CLAY_BOILERPLATE.substitute(
			extern_declarations = "\n".join(self.declarations),
			test_callbacks = "\n".join(self.callbacks),
			test_suites = ",\n\t".join(self.suites.values())
		)

	def _cleanup_name(self, name):
		words = name.split("_")
		return " ".join(words).capitalize()


	def _process_test_file(self, file_name, contents):
		file_name = os.path.basename(file_name)
		file_name, _ = os.path.splitext(file_name)

		regex_string = TEST_FUNC_REGEX % file_name
		regex = re.compile(regex_string, re.MULTILINE)

		callbacks = {}

		for (declaration, symbol, short_name, _) in regex.findall(contents):
			self.declarations.append("extern %s;" % declaration)

			callbacks[short_name] = '{"%s [%s]", &%s}' % (
				self._cleanup_name(short_name), symbol, symbol
			)

		initialize = callbacks.pop("initialize", "NULL")
		cleanup = callbacks.pop("cleanup", "NULL")

		if not callbacks:
			return

		self.callbacks.append(TEMPLATE_CALLBACKS.substitute(
			suite_name = file_name,
			callbacks = ",\n\t".join(callbacks.values())
		).strip())

		self.suites[file_name] = TEMPLATE_SUITE.substitute(
			clean_name = self._cleanup_name(file_name),
			suite_name = file_name,
			initialize = initialize,
			cleanup = cleanup,
			test_count = len(callbacks)
		).strip()

if __name__ == '__main__':
	builder = ClayTestBuilder('.')
	print builder.render()
