name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
